image: golang:1.11.5

variables:
  GIT_URL: gitlab.com
  GITHUB_REPO: gmantaos/Goirate

stages:
- test
- build
- deploy

before_script:
# Prepare workspace
- mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
- rm -rf "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}" || true
- ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
- cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
- make install-tools

test:
  stage: test
  retry: 2
  tags:
  - freya
  script:
  - make lint
  - make test-cov
  - mv build/* ${CI_PROJECT_DIR}/
  artifacts:
    name: test_coverage
    paths:
    - test_coverage.*

build:
  stage: build
  script:
  - make clean
  - make cross-compile

github-release:
  stage: deploy
  only:
  - tags
  dependencies:
  - build
  script:
  - go get -u github.com/c4milo/github-release
  - github-release $GITHUB_REPO "$CI_COMMIT_TAG" "master" "$CI_COMMIT_DESCRIPTION" "build/goirate.*"
