
image: golang

variables:
  GIT_URL: "git.gmantaos.com"

stages:
  - build
  - test

before_script:  
  # Install dep
  - go get -d -u github.com/golang/dep
  - cd $(go env GOPATH)/src/github.com/golang/dep
  - DEP_LATEST=$(git describe --abbrev=0 --tags)
  - git checkout -q $DEP_LATEST
  - go install -ldflags="-X main.version=$DEP_LATEST" ./cmd/dep

  # Prepare workspace
  - mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
  - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
  - cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"

compile:
  stage: build
  script:
    - make

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet -composites=false $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/) -v -coverprofile .testCoverage.txt