
image: golang

variables:
  GIT_URL: "git.gmantaos.com"

before_script:  
  # Install dep
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

  # Prepare workspace
  - mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
  - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
  - cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"

build:
  stage: build
  script:
    - make