image: gmantaos/golang-dep-arm

variables:
  GIT_URL: git.gmantaos.com
  GITHUB_REPO: gmantaos/Goirate

stages:
- test
- build
- deploy

before_script:
# Prepare workspace
- mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
- rm -rf "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}" || true
- ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
- cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"

test:
  stage: test
  retry: 2
  tags:
  - arm
  script:
  - make lint
  - make test-cov
  - mv build/* ${CI_PROJECT_DIR}/
  artifacts:
    name: test_coverage
    paths:
    - test_coverage.*

github-release:
  stage: deploy
  only:
  - tags
  tags:
  - amd64
  script:
  - make clean
  - make cross-compile
  - go get -u github.com/c4milo/github-release
  - github-release $GITHUB_REPO "$CI_COMMIT_TAG" "master" "$CI_COMMIT_DESCRIPTION" "build/goirate.*"