
image: golang

variables:
  NAMESPACE_PATH: "git.gmantaos.com/${CI_PROJECT_NAMESPACE}"
  PROJECT_PATH: "${NAMESPACE_PATH}/${CI_PROJECT_NAME}"

before_script:
  - go get github.com/tools/godep
  
  - mkdir -p "${GOPATH}/src/${NAMESPACE_PATH}"
  - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${PROJECT_PATH}"
  - cd "${GOPATH}/src/${PROJECT_PATH}""

build:
  stage: build
  script:
    - godep restore