image: gmantaos/golang-dep-arm

variables:
  GIT_URL: "git.gmantaos.com"

stages:
  - test
  - build

before_script:
  # Prepare workspace
  - mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
  - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
  - cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"

  - make dep

lint:
  tags:
    - windows
  stage: test
  script:
    - make lint

test:
  tags:
    - windows
  stage: test
  script:
    - make test-cov
    - mv build/* .
  artifacts:
    name: test_coverage
    paths:
      - test_coverage.*
    expire_in: 1 week

compile:
  tags:
    - windows
  stage: build
  script:
    - make build
    - mv build/* .
  artifacts:
    name: goirate
    paths:
      - goirate
    expire_in: 1 week