image: golang-dep

variables:
  GIT_URL: "git.gmantaos.com"

stages:
  - prepare
  - test
  - build

before_script:  
  # Prepare workspace
  - mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
  - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
  - cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"

build-image:
  stage: prepare
  script
    - "curl -X POST -F token=$TRIGGER_TOKEN -F ref=master https://git.gmantaos.com/api/v4/projects/35/trigger/pipeline"

format:
  stage: test
  script:
    - make test

compile:
  stage: build
  script:
    - make build
  artifacts:
    paths:
    - build/
    expire_in: 1 week