image: golang-dep

variables:
  GIT_URL: "git.gmantaos.com"

stages:
  - test
  - build

before_script:  
  # Prepare workspace
  - mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
  - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
  - cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"

format:
  stage: test
  script:
    - make test

compile:
  stage: build
  script:
    - make build
  artifacts:
    paths:
    - build/
    expire_in: 1 week