image: gmantaos/golang-dep-arm

variables:
  GIT_URL: "git.gmantaos.com"

stages:
  - test
  - build

before_script:
  # Prepare workspace
  - mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
  - rm -rf "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}" || true
  - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
  - cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"

lint:
  stage: test
  script:
    - make lint

test:
  stage: test
  retry: 2
  script:
    - make test-cov
    - mv build/* ${CI_PROJECT_DIR}/
  artifacts:
    name: test_coverage
    paths:
      - test_coverage.*
    expire_in: 1 week

build-armhf:
  stage: build
  only:
    - tags
  tags:
    - arm
    - x32
  script:
    - make build
    - ./build/goirate --version
    - ./scripts/publish.sh armhf
    - mv build/* ${CI_PROJECT_DIR}/
  artifacts:
    name: goirate.armhf
    paths:
      - goirate

build-aarch64:
  stage: build
  only:
    - tags
  tags:
    - arm
    - x64
  script:
    - make build
    - ./build/goirate --version
    - ./scripts/publish.sh aarch64
    - mv build/* ${CI_PROJECT_DIR}/
  artifacts:
    name: goirate.aarch64
    paths:
      - goirate

build-win64:
  stage: build
  only:
    - tags
  tags:
    - windows
  script:
    - make build
    - ./build/goirate --version
    - ./scripts/publish.sh win64
    - mv build/* ${CI_PROJECT_DIR}/
  artifacts:
    name: goirate.win64
    paths:
      - goirate