image: gmantaos/golang-dep-arm

variables:
  GIT_URL: git.gmantaos.com
  ROCKET_LAST_TAG: ${CI_COMMIT_TAG}
  ROCKET_GIT_REPO: gmantaos/Goirate

stages:
  - test
  - build
  - deploy

before_script:
  # Prepare workspace
  - mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
  - rm -rf "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}" || true
  - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
  - cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"

test:
  stage: test
  retry: 2
  script:
    - make lint
    - make test-cov
    - mv build/* ${CI_PROJECT_DIR}/
  artifacts:
    name: test_coverage
    paths:
      - test_coverage.*

build-armhf:
  stage: build
  tags:
    - arm
    - x32
  script:
    - make build
    - mv ./build/goirate ./build/goirate.armhf
  artifacts:
    expire_in: 1h
    paths: 
      - ./build/goirate.armhf

build-aarch64:
  stage: build
  tags:
    - arm
    - x64
  script:
    - make build
    - mv ./build/goirate ./build/goirate.aarch64
  artifacts:
    expire_in: 1h
    paths: 
      - ./build/goirate.aarch64

build-win64:
  stage: build
  tags:
    - windows
  script:
    - make build-win64
    - mv ./build/goirate ./build/goirate.win64.exe
  artifacts:
    expire_in: 1h
    paths: 
      - ./build/goirate.win64.exe

publish:
  stage: deploy
  only:
    - tags
  script:
    - go get -u github.com/astrocorp42/rocket
    - rocket