image: golang-dep

variables:
  GIT_URL: "git.gmantaos.com"

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in


stages:
  - test
  - build

before_script:  
  # Prepare workspace
  - mkdir -p "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_NAMESPACE}"
  - ln -s "${CI_PROJECT_DIR}" "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"
  - cd "${GOPATH}/src/${GIT_URL}/${CI_PROJECT_PATH}"

  - make dep
  - chmod +x ./scripts/test.sh

  - echo $GOPATH

test:
  stage: test
  script:
    - make test-cov

lint:
  stage: test
  script:
    - make lint

compile:
  stage: build
  script:
    - make build