
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "gitlab.com/haath/gobytes"
  version = "1.1.1"
  
[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.13.7"

[[constraint]]
  branch = "master"
  name = "github.com/inconshreveable/go-update"

[[constraint]]
  branch = "master"
  name = "github.com/jaredlmosley/go-qbittorrent"
